[server]
headless = true
port = 8501
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
